### ISSUE TITLE
How to set the minWith correctly?

### ISSUE THREAD

**Issue by michealchow2324** [Codelessly/ResponsiveFramework#19]
For example if i was using Iphone SE to build the layout, what is the proper value for **minWidth** ?
```
ResponsiveWrapper(
    child,
    maxWidth: 1200,
    minWidth: 480,
    defaultScale: true,
    breakpoints: [
        ResponsiveBreakpoint.resize(480, name: MOBILE),
        ResponsiveBreakpoint.autoScale(800, name: TABLET),
        ResponsiveBreakpoint.resize(1000, name: DESKTOP),
        ResponsiveBreakpoint.autoScale(2460, name: '4K'),
    ],
)
```

**Comment by searchy2** [comment]
Depends on the design. 

I usually use a value between 360 to 480. 

Find the smallest width above 360 that looks good and use that as the min width.

**Comment by michealchow2324** [comment]
Because some layouts are oversize in different device when i set the minWidth to 480, and i don't know if it is a normal behaviour.

**Comment by searchy2** [comment]
Find the smallest width that your layout looks good on and set that as the min width. 
Can you try setting 400? That's a good default value.

**Comment by michealchow2324** [comment]
thanks , i think i got it.

**Comment by searchy2** [comment]
Great! Closing this issue as solved. Please feel free to open.

**Comment by gOzaru** [comment]
@michealchow2324 
I think the minWidth is the default size of the device you used for testing purpose. 
For example: 
I have a smartphone 720 x 1440. 
Before I used the Responsive package, I had to check the width calculated by `MediaQuery.of(context).size.width` at first. After I know the value, I used that to setup all of the layout design based on that width and height. And apparently, the value was 360. So I set it as minWidth with defaultScaleFactor as 1.0.
Overall, you can make it like this:
```dart
minWidth: 360,
defaultName: MOBILE,
defaultScale: true,
breakpoints: const [
  ResponsiveBreakpoint.autoScale(360, scaleFactor: 1.0),
  ResponsiveBreakpoint.resize(720, scaleFactor: 1.75),  //720 : 360 = 2.0 
  ResponsiveBreakpoint.resize(900, scaleFactor: 2.0),  //900 : 360 = 2.5
  ResponsiveBreakpoint.autoScale(1080, scaleFactor: 2.4), //1080 : 360 = 3
  ResponsiveBreakpoint.autoScale(1800, scaleFactor: 3.0), //1800 : 360 = 5
],
```

In order to get the same layout design for all types of devices, we need to count all of the value using `MediaQuery.of(context).size.width`. After that, we devide the value with minWidth and get the value of scaleFactor. By the way, if you noticed on the above code, I didn't set the exact multiplication on breakpoint 720, 900 and above. It should bd 2.0 for 720. But I set it lower as after testing, I found out it was too big. So I scaled it down around 10% - 25%. Of course, you have to do a research about this for the best scaleFactor for you.
