### ISSUE TITLE
Shadow behind pages

### ISSUE THREAD

**Issue by pedromassango** [Codelessly/ResponsiveFramework#30]
Hey great package!

I just added it following the Readme, and it shows this shadow behind my pages. Note that if I remove the code of this package the shadow disppear so I suspect that this is an issue within the package. I've tried to find the cause but had no luck.

![Screen Shot 2020-11-23 at 18 47 20](https://user-images.githubusercontent.com/33294549/99996734-6fef7e00-2dbc-11eb-87be-d0d995580d41.png)

**Comment by searchy2** [comment]
You're setting a max width and the shadow is the default MaterialApp navigation shadow.
Usually, the shadow is hidden because the edge of the UI is flush with the edge of the screen. Now that the UI is not, you can see the shadow.

The solution is to override the Material navigation if you want to get rid of the shadow.
https://github.com/Codelessly/FlutterMinimalWebsite/blob/3c27638817a2547c79738aceed647f70ff824d92/lib/main.dart#L29

**Comment by pedromassango** [comment]
Sorry, it is still not clear to me what the solution is. Tried to override **onGenerateRoute** and provide a custom route but the shadow still there

**Comment by searchy2** [comment]
Oh right, can you try setting the theme to Android? 
      `theme: Theme.of(context).copyWith(platform: TargetPlatform.android)`
