### ISSUE TITLE
Will there be desktop like Ui support ???

### ISSUE THREAD

**Issue by fisforfaheem** [Codelessly/ResponsiveFramework#33]
it would be cool to see desktop ui automatically infl flutter

**Comment by searchy2** [comment]
What do you mean by Desktop UI? What is an example?

**Comment by searchy2** [comment]
Please reopen if you are able to provide more information.

**Comment by jlnrrg** [comment]
@searchy2 
He might have been talking about the prevention on specific platforms.
Rn one can setup my `ResponsiveBreakpoints` how I want, and they translate marvalous onto every plattform.
This unfortunately is active on all plattforms. It would be great to have in all the `ResponsiveBreakpoint`s a list for `preventOnPlatforms` of type `List<ResponsiveTargetPlatform>`, so I can disable specific breakpoints on certain plattforms.

Giving, that one has setup the breakpoints to support a lot of different settings, then these are also recognized on deskop:

https://user-images.githubusercontent.com/77293597/142737030-5e0b5b04-a57e-4117-bb16-0db8197c4aac.mp4


(I know one could disable the `ResponsiveWrapper` on specific platforms, but might want to access the breakpoints further down the widget tree anyway)

**Comment by jlnrrg** [comment]
Also I noticed that the `ResponsiveWrapper` sometimes does not scale on the right breakpoint, if I scale just the width for example.

For a quick and dirty fix, you could expose the `key` and then one could pass a `ValueKey<double>(constraints.maxWidth)` even though it was outlined [here](https://github.com/letsar/flutter_staggered_grid_view/issues/167#issuecomment-961937316), why that is performance wise a bad decision.

**Comment by searchy2** [comment]
@jlnrrg I 100% agree with your suggestions. 
There's a v0.3.0 planned for those features. 

What do you think about the idea of removing breakpoints and instead have breakpoint segments that allow you to control the behavior instead? 
For example, instead of setting a breakpoint at 480, you would instead specify the behavior from 480 - 779. 
I'm considering making this change because it would allow the removal of the complex segments algorithm and simply usage. So instead of having to understand how the library works, developers would be able to specify EXACTLY what happens at each segment. This would also enable support of per platform, per page, and even per widget settings.

I'd love to hear your thoughts and continue this discussion under a new issue.
