### ISSUE TITLE
Improvement request.

### ISSUE THREAD

**Issue by iamsannyrai** [Codelessly/ResponsiveFramework#47]
Hey @searchy2 ! Thank you for search a great package.
I have one improvement request.

As per the implementation, it is obvious that children of ResponsiveRowColumn gets rebuilt every time we resizes our app (in my case its web app).

For example, suppose we have one StatefulWidget widget as one of the children and it makes network call in its initState() method. Then each time when we resizes our app, then its initstate method is going to run again (given that rowColumn flag must be satisfied though).

Can you make workaround to prevent this?

Thank you.

**Comment by searchy2** [comment]
Thank you.

Widgets will be rebuild on resize unless they are declared as const. Flutter does an identity check for widgets that listen to resize. If the new widget is equal to the old widget, didUpdateWidget is called instead of initState. 

You should not put network calls in initState.

It is possible I'm not declaring const children so I will look into if ResponsiveRowColumn is incorrectly recreating child widgets.

**Comment by iamsannyrai** [comment]
Thanks for the reply. The case where didUpdateWidget would work is when we have children still in the widget tree. But don't you think that when (assumption) your browser resizes from Desktop mode to Mobile mode, the children of ResponsiveRowColumn which are ResponsiveRowColumnItems get destroyed when condition is not met.
For example:
Consider you have two children currently in row in desktop mode. Now when you switch to mobile mode, then these two children get disposed (removed from widget tree), and creates new one again to display in column.

**Comment by searchy2** [comment]
Adding to my TODO to investigate.

**Comment by iamsannyrai** [comment]
Ya sure. For now I will close this issue.
